### PR TITLE
Use controller-runtime setup-envtest and generate junit report in ci-test.sh

### LINKED ISSUE #498: Use controller-runtime setup-envtest instead of fetch_ext_bins.sh and generate junit report in ci-test.sh
/kind feature

**Describe the solution you'd like**
 there is a tool by controller-runtime which can be used to setup the controller-runtime envtest binaries (https://github.com/kubernetes-sigs/controller-runtime/tree/master/tools/setup-envtest).
It's already used in core CAPI: https://github.com/kubernetes-sigs/cluster-api/blob/main/Makefile#L437-L441

It will be good if we add this to CAPG  to make the contributor experience more similar.

### PR DESCRIPTION
**Pull request by sayantani11**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #498 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Use controller-runtime setup-envtest and generate junit report in ci-test.sh
```

### CODE REVIEW

**Comment by sayantani11** [comment]
The problem is here: https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/scripts/ci-test.sh#L26
And the errors are related, as I see in CAPI they have added a different way of testing.

**Comment by sayantani11** [comment]
cc @cpanato

**Review by cpanato — APPROVED** [review]
thanks!!
/lgtm
/approve

**Pull request merged**
