### PR TITLE
feat: Add support for feature gates

### LINKED ISSUE #643: Enable Feature Gates
/kind feature

**Describe the solution you'd like**
Other providers support feature gates (ex. [AWS](https://github.com/kubernetes-sigs/cluster-api-provider-aws/tree/main/feature) and [Azure](https://github.com/kubernetes-sigs/cluster-api-provider-azure/tree/main/feature)).  It'd be good to align this wiring with the other CSPs.  This will be needed to support additional functionality and features in the future.

### PR DESCRIPTION
**Pull request by evanfreed**
**What type of PR is this?**

**What this PR does / why we need it**:
Adds the ability to use feature gates.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #643 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Adding features via feature gate
```

/feature

Signed-off-by: Evan Freed <evan.freed@protonmail.ch>

### CODE REVIEW

**Comment by sayantani11** [comment]
@evanfreed Please run `make modules` and `make verify-modules` and try pushing the PR again.

**Comment by evanfreed** [comment]
Sorry for the delay, I had some time off so I didn't look at this.  I repushed after running `make modules`and `make verify-modules`.  Looks like there was an update to the go mod file, must have snuck in with a different commit but should be fixed up 🤞

**Comment by eaceaser** [comment]
Hi! I'm working on a PR where I would love to feature gate support -- is there anything I can do to help this PR get merged?

**Comment by evanfreed** [comment]
@eaceaser sorry for the delay in response, I was on vacation for a bit.  I think we're good here now that I rebased, I'm just waiting for a review.

**Comment by evanfreed** [comment]
@sayantani11 @fabriziopandini  or @sbueringer would you be willing to take a look? 🙏 thanks in advanced

**Comment by sbueringer** [comment]
/cc @cpanato 

@evanfreed Fabrizio and I are mostly in the reviewer list because maintainers of core CAPI where synced into the OWNERS file of CAPG.

**Comment by evanfreed** [comment]
No worries! Thanks @sbueringer

**Comment by evanfreed** [comment]
@pydctw is there a chance you'd be able to look at this?  I'm struggling to find a reviewer.

**Comment by pydctw** [comment]
sure. thanks for adding the feature gate support, @evanfreed 
/lgtm

**Review by cpanato — APPROVED** [review]
looks cool
thanks
/approve

**Pull request merged**
