### PR TITLE
Add nodeManagement field to GCPManagedMachinePool

### PR DESCRIPTION
**Pull request by kahun**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This PR adds the nodeManagement field to the GCPManagedMachinePool object to manage the update management configuration in GKE pools.

**TODOs**:
- [X] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by richardcase** [comment]
Thanks @kahun . The **NodeManagement** options are already covered by an open PR (#1026).

Until we see if that PR merges:

/hold

**Comment by kahun** [comment]
> Thanks @kahun . The **NodeManagement** options are already covered by an open PR (#1026).
> 
> Until we see if that PR merges:
> 
> /hold

I know, but I thought this would be more atomic and easier to merge. I'm also interested in the improvement of the status included in that PR. It's ok to wait and see if #1026 is merged. 

Thanks

**Comment by richardcase** [comment]
> It's ok to wait and see if #1026 is merged.

@kahun - the PR just merged. If you could look and then decide if this PR needs closing or updating.

**Comment by kahun** [comment]
> > It's ok to wait and see if #1026 is merged.
> 
> @kahun - the PR just merged. If you could look and then decide if this PR needs closing or updating.

I am going to test it and let you know. Thanks.

**Comment by kahun** [comment]
This PR is no longer necessary.

Thanks.

**Pull request closed without merging**
