### PR TITLE
golangci-lint: update golangci rules and fix the lints

### PR DESCRIPTION
**Pull request by cpanato**
Signed-off-by: Carlos Panato <ctadeu@gmail.com>

 

 
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

golangci-lint: update golangci rules and fix the lints

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes: https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/368

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
/approve
/lgtm

Do we want to add a github action to run these checks?

**Comment by cpanato** [comment]
@dims It already runs in the `pull-cluster-api-provider-gcp-test` job: it run the ci-test.sh and it calls the make lint: https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/Makefile#L212

but if we want to make it more explicitly I can remove it from there and add a GH action, which sounds good, let me know your thoughts

**Comment by dims** [comment]
ah, i missed that. +1 to GH action though. harder for folks to dig into prow based CI failures

**Comment by cpanato** [comment]
will do and remove the call from the prow job

**Pull request merged**
