### PR TITLE
Fix apidiff target

### LINKED ISSUE #592: Enable apidiff to report only actual API changes
/kind bug

**What steps did you take and what happened:**
Recently added apidiff reports any changes in exposed field/function as breaking changes. 

As an example, one of recent [PR test](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-gcp/587/pull-cluster-api-provider-gcp-apidiff/1518554081407275008) fails with the following output, which doesn't have any API changes.
```bash
*** Running go-apidiff ***
sigs.k8s.io/cluster-api-provider-gcp/cloud/services/compute/instances
  Incompatible changes:
  - MachineGetter.Project: added
sigs.k8s.io/cluster-api-provider-gcp/cloud
  Incompatible changes:
  - MachineGetter.Project: added
sigs.k8s.io/cluster-api-provider-gcp/cloud/scope
  Compatible changes:
  - (*MachineScope).Project: added
...
```

**What did you expect to happen:**
apidiff should only inform about API changes within `api/` directory

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>

 

 
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
- Bump apidiff version to v0.4.0
- Fix apidiff target to report only actual api changes

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #592 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Fix apidiff target
```

### CODE REVIEW

**Comment by pydctw** [comment]
Thanks for fixing the issue 🎉

/lgtm

**Comment by pydctw** [comment]
@cpanato for approval

**Comment by Prajyot-Parab** [comment]
@pydctw For your review, just force-pushed (no changes in code)

**Pull request merged**
