### PR TITLE
Doc about Persistent disk added

### PR DESCRIPTION
**Pull request by sayantani11**
**What type of PR is this?**

**What this PR does / why we need it**:
This PR adds documentation how persistent disks should be provisioned and attached to VMs in Google Cloud Platform.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Persistent disk documentation
```

### CODE REVIEW

**Comment by sayantani11** [comment]
#451

**Comment by shivanshu1333** [comment]
Hey, it's a good practice to link the issue using `Ref: <issue>` in PR description, whenever the PR is subpart of the issue.

**Comment by sayantani11** [comment]
@cpanato guess this should work

**Comment by cpanato** [comment]
> @cpanato guess this should work

can you run and post the results to we make sure that works?

**Pull request closed without merging**
