### PR TITLE
Align kubectl install and CI scripts to use local bin folder

### LINKED ISSUE #484: Align kubectl install and CI scripts to use local bin folder
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
There are two different ways the repository installs tools. It would be better to align to install all tools via `makefile` into a `hack/tools/bin` and have all scripts use those tools.

**What did you expect to happen:**
`make` and CI scripts all use the same version of tooling from local path.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Similar changes have been done to [Azure](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1192)

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by sayantani11**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #484 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Align kubectl install and CI scripts to use local bin folder
```

### CODE REVIEW

**Comment by sayantani11** [comment]
@cpanato Can you please look into the e2e-test error? I went through the logs but I am still unable to figure out what actually is going wrong.

**Comment by sayantani11** [comment]
@cpanato Is the e2e test flaky?

**Comment by cpanato** [comment]
@sayantani11 rebase your PR with latest main branch , this was fixed, was a cert manager error in capi

**Review by cpanato — APPROVED** [review]
thanks!
/lgtm
/approve

**Pull request merged**
