### PR TITLE
✨ Add externally managed predicate to GCPCluster controller

### PR DESCRIPTION
**Pull request by asalkeld**
/kind feature

**What this PR does / why we need it**:
This PR implements https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20210203-externally-managed-cluster-infrastructure.md for the GCP provider.

**Release note**:
```release-note
GCP provider now supports the externally managed annotation as documented here https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20210203-externally-managed-cluster-infrastructure.md
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/approve

thanks for this PR

**Comment by cpanato** [comment]
checking why the conformance is broken

**Comment by asalkeld** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-gcp/372/pull-cluster-api-provider-gcp-make-conformance/1401864867656241152#1:build-log.txt%3A1148
```
/usr/bin/timeout 15m bash -c "while ! kubectl --kubeconfig="/tmp/kubeconfig" get nodes | grep master; do sleep 1; done"
Error from server (InternalError): an error on the server ("") has prevented the request from succeeding 
```
not a very helpful error :thinking:

**Comment by cpanato** [comment]
testing here: https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/373 and seems that is running will try it again

/test pull-cluster-api-provider-gcp-make-conformance

**Comment by cpanato** [comment]
looks like was some infra failures 🤷

**Pull request merged**
