### PR TITLE
update capi to release v0.4.8

### PR DESCRIPTION
**Pull request by cpanato**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

- update capi to release v0.4.8
after this we will release it

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
update capi to release v0.4.8
```

### CODE REVIEW

**Comment by cpanato** [comment]
need this change in test-infra https://github.com/kubernetes/test-infra/pull/25577

**Comment by cpanato** [comment]
/hold for the conformance tests
/assign @dims 

after we merge this I will prepare the release

**Comment by dims** [comment]
/approve
/lgtm

feel free to remove hold when ready @cpanato

**Pull request merged**
