### PR TITLE
Add documentation for nightly builds

### PR DESCRIPTION
**Pull request by damdo**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
📖 Add documentation for nightly builds

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by cpanato — CHANGES_REQUESTED** [review]
lgtm

just need to fix the misspell

**Comment by damdo** [comment]
@cpanato  Misspell is not from this PR, but was fixed by: https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/1233 when it merged.
I just rebased on top of main so it resolved now.
Could you re LGTM/approve? Thanks!

**Review by cpanato — APPROVED** [review]
thanks

/lgtm
/approve

**Pull request merged**
