### PR TITLE
🏃 Deprecate hack tools go mod

### PR DESCRIPTION
**Pull request by cpanato**
**What this PR does / why we need it**:

Deprecate the hack/tools go mod

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by rsmitty** [comment]
A lot going on here, but looks like it's mostly addressing linter warnings. LGTM. Thanks for doing all this cleanup work!

**Comment by cpanato** [comment]
@rsmitty ready, the fail test in the conformance test is the same and it is not related to the changes in this PR

**Pull request merged**
