### PR TITLE
Bump CAPI to v1.8

### PR DESCRIPTION
**Pull request by damdo**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

CAPI v1.8.0 is out now, so this PRs bumps the CAPI version used by CAPG to it.

Bumps CAPI to v1.8.x based on https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/book/src/developer/providers/migrations/v1.7-to-v1.8.md

**Special notes for your reviewer**:
api-diff failing is expected as the API changed to a typed go generics function.

**Checklist**:

- [x] squashed commits
- [x] adds or updates e2e tests

**Release note**:
```release-note
Bump CAPI to v1.8.4
```

### CODE REVIEW

**Comment by damdo** [comment]
api-diff failing is expected as the API changed to a typed go generics function.

**Comment by richardcase** [comment]
Thanks @damdo for this

**Review by cpanato — APPROVED** [review]
this is great, thank you

i will plan a release for that, do y'all agree?

**Comment by damdo** [comment]
Yes a release would be awesome @cpanato thanks!

**Comment by richardcase** [comment]
> i will plan a release for that, do y'all agree?

That would be great 👍

**Pull request merged**
