### PR TITLE
Make GKE enableAutopilot optional

### PR DESCRIPTION
**Pull request by akshay196**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Make GKE enableAutopilot field optional.

Error out otherwise:
```
error: error validating "capi-gke-quickstart.yaml": error validating data: ValidationError(GCPManagedControlPlane.spec): missing required field "enableAutopilot" in io.x-k8s.cluster.infrastructure.v1beta1.GCPManagedControlPlane.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

None

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [X] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by richardcase** [comment]
Thanks for this @akshay196 .

I think that we should make the field optional instead. This can be done by using the `+optional` comment annotation like this: https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/exp/api/v1beta1/gcpmanagedcontrolplane_types.go#L50

**Comment by akshay196** [comment]
@richardcase Is this OK to test now?

**Comment by akshay196** [comment]
All test are passing. 🎉 
@cpanato @richardcase Let me know if any comments.

**Review by cpanato — COMMENTED** [review]
/approve
/assign @richardcase

**Comment by akshay196** [comment]
@cpanato @richardcase Any updates? Let me know if anything needed.

**Pull request merged**
