### PR TITLE
dev-workflow: add tilt and documentation to develop capg 

### PR DESCRIPTION
**Pull request by cpanato**
**What type of PR is this?**

/kind feature
/kind documentation

**What this PR does / why we need it**:
dev-workflow: add tilt and documentation to develop capg 

/assign @dims 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [x] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
dev-workflow: add tilt and documentation to develop capg 
```

### CODE REVIEW

**Comment by dims** [comment]
/approve
/lgtm

cc @Ankitasw 

Ankita, can you please try this out and file any follow up PRs?

**Comment by cpanato** [comment]
thanks for the review @dims!

**Comment by Ankitasw** [comment]
thankyou @cpanato for this PR , its very useful for dev testing.

**Pull request merged**
