### PR TITLE
update CAPI dependency to v0.3.16

### PR DESCRIPTION
**Pull request by cpanato**
**What type of PR is this?**

/kind feature
/kind cleanup

**What this PR does / why we need it**:

update CAPI dependency to v0.3.16

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes as well https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/359

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
update CAPI dependency to v0.3.16
```

### CODE REVIEW

**Review by vincepri — APPROVED** [review]
/approve
/lgtm

**Comment by vincepri** [comment]
/lgtm cancel

per above

**Comment by cpanato** [comment]
@vincepri I'm debugging why it is failing now, will take a bit more time :/

**Comment by cpanato** [comment]
now it is green @vincepri :-)

can you please take another look?

**Comment by cpanato** [comment]
this test `pull-cluster-api-provider-gcp-e2e-test` can be ignored, this was misconfigured and that should run only for the main branch, not for the release-0.3 branch

**Comment by cpanato** [comment]
/hold cancel

will make a release for 0.3 tomorrow

**Comment by cpanato** [comment]
will update capi to 0.3.17 before the release

**Pull request merged**
