### PR TITLE
Fixed broken links // prerequisites, development guide

### LINKED ISSUE #424: Multiple links in `README.md` are broken.
/kind bug
/kind documentation

**What steps did you take and what happened:**
Multiple links are broken in the `README.md` file. You'll have to check one by one and attach the link of the mentioned file wherever necessary.

**What did you expect to happen:**
The links should direct to the mentioned page.

### PR DESCRIPTION
**Pull request by harshmathurx**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:
Fixed 2 broken links - prerequisites and development guide

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #424 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [x] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sayantani11** [comment]
LGTM!
Thanks for the PR @harshmathurx

**Comment by harshmathurx** [comment]
> 
> 
> LGTM! Thanks for the PR @harshmathurx

you're welcome 
looking forward to contributing more :)

**Review by cpanato — APPROVED** [review]
thanks for the fix!
/approve
/lgtm

**Pull request merged**
