### PR TITLE
Add docs (GKE part 8)

### PR DESCRIPTION
**Pull request by richardchen331**
/kind documentation

**What this PR does / why we need it**:
This change adds relevant docs for the GKE feature in CAPG.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Relates #512

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Add documentation for the GKE feature
```

### CODE REVIEW

**Review by cpanato — COMMENTED** [review]
thank you!
/approve
/assign @richardcase

**Comment by richardcase** [comment]
Thanks @richardchen331 

/lgtm

**Pull request merged**
