### PR TITLE
🐛 fix conformance job

### PR DESCRIPTION
**Pull request by cpanato**
**What this PR does / why we need it**:
This PR fix the conformance job

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes/kubernetes/issues/95729

### CODE REVIEW

**Comment by cpanato** [comment]
There are other improvements we can do here, like converting to use the framework to run the conformance tests, but I don't know the history behind this way, so I will try to discuss this in the cluster-api channel to see with we want to change and make more similar to the other providers

**Comment by cpanato** [comment]
The fix in the PR is just to get the job back on track

**Comment by rsmitty** [comment]
@cpanato sounds good to me. feel free to ping me to discuss. I'd love to see us get this back on track and cut a release (I'll need to learn how to do that from detiber).

**Review by neolit123 — COMMENTED** [review]
thanks for the PR, the change looks fine to me but i'n not familiar to the setup here overall.
would appreciate LGTM from someone.

/approve

**Comment by rsmitty** [comment]
ping for @detiber or @vincepri if either of you guys have a free cycle to approve this

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
