### PR TITLE
fix: The subject was incorrectly used in some parts of the document.

### PR DESCRIPTION
**Pull request by kahirokunn**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [x] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
fix: The subject was incorrectly used in some parts of the document.
```

### CODE REVIEW

**Review by cpanato — COMMENTED** [review]
/ok-to-test

**Review by cpanato — APPROVED** [review]
thanks

/approve
/lgtm

**Comment by kahirokunn** [comment]
thanks

**Pull request merged**
