### PR TITLE
Fixed broken link in releasing.md

### LINKED ISSUE #620: Link-check test failing due to a broken link.
/kind bug

**What steps did you take and what happened:**
Link-check/Broken Links test is failing due to a broken link in [releasing.md](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/docs/book/src/developers/releasing.md).

**What did you expect to happen:**
The correct link should be added so the test could pass.

**Anything else you would like to add:**
At line 17, the existing link should be replaced with `https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key`

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Aayush987**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
This PR removes the broken link from the `releasing.md` file and replaced with a valid one. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #620

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note

```

### CODE REVIEW

**Review by jayesh-srivastava — APPROVED** [review]
lgtm!

**Comment by hrittikhere** [comment]
Hey @jayesh-srivastava we have this as a duplicate for https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/613

I was requested to fix the broken link as well :)

**Comment by cpanato** [comment]
since this pr is fixing broken links, I would say we fix all broken links and then we can merge this.

**Comment by Aayush987** [comment]
> > > since this pr is fixing broken links, I would say we fix all broken links and then we can merge this.
> > 
> > Do i have to do something from my side?
> 
> find the other broken links and get those updated :)

Ok, i will look for broken links in other files and get those updated.

**Comment by Aayush987** [comment]
Closing this pr, since the issue is already solved.

**Pull request closed without merging**
