### PR TITLE
Update k8s to use 1.20 release for e2e tests

### PR DESCRIPTION
**Pull request by cpanato**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:
- update go to 1.16.7
- update golangci-lint to v1.41.1

- Use k8s 1.20 release to run the e2e tests

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
- Use k8s 1.20 release to run the e2e tests
```

### CODE REVIEW

**Comment by cpanato** [comment]
need this https://github.com/kubernetes/test-infra/pull/23206
/hold

**Comment by dims** [comment]
/approve
/lgtm

please feel free to remove hold when the linked one merges.

**Pull request merged**
