### PR TITLE
Upgrade golang to v1.18.3

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>

 

 
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
- Upgrade golang to v1.18.4

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Upgrade golang to v1.18.4
```

### CODE REVIEW

**Comment by Prajyot-Parab** [comment]
@cpanato @CecileRobertMichon any pointers on fixing the verify prow job?

**Comment by Prajyot-Parab** [comment]
> @cpanato any pointers on fixing the verify prow job failure?

/hold

Needs to merge - [#26865](https://github.com/kubernetes/test-infra/pull/26865), to be able to run verify job.

**Comment by cpanato** [comment]
I know that @jayesh-srivastava was working on this update (https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/580) but I'm not sure what the status is.

@jayesh-srivastava is it okay to @Prajyot-Parab take this over?

**Comment by cpanato** [comment]
one question, CAPI is on go1.18 already? otherwise why we are moving to go1.18?

**Comment by Prajyot-Parab** [comment]
> one question, CAPI is on go1.18 already? otherwise why we are moving to go1.18?

Yes CAPI is on go1.18 already.

**Comment by jayesh-srivastava** [comment]
@cpanato Took some time off, yes will work on this and update you soon. If I am unable to finish this, will ping @Prajyot-Parab so they can takeover. I hope this is okay.

**Comment by cpanato** [comment]
can you rebase to get the fixes from https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/671?
thanks

**Comment by Prajyot-Parab** [comment]
> can you rebase to get the fixes from #671?
> thanks

Done. All the jobs should pass now.
I think we are good state to merge this one, I don't see any updates on other PR as well.

**Comment by cpanato** [comment]
@Prajyot-Parab can you please rebase and then we can merge it? thanks

**Comment by Prajyot-Parab** [comment]
> @Prajyot-Parab can you please rebase and then we can merge it? thanks

Done.

**Review by cpanato — APPROVED** [review]
/hold for the periodic job update

/approve
/lgtm

**Comment by cpanato** [comment]
@Prajyot-Parab can you now open a PR to update the periodic job? :)
thanks for working on this 🎉

**Comment by Prajyot-Parab** [comment]
> @Prajyot-Parab can you now open a PR to update the periodic job? :)
> thanks for working on this 🎉

will do.

**Pull request merged**
