### PR TITLE
Update go version to 1.18.1

### PR DESCRIPTION
**Pull request by jayesh-srivastava**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Updates go version to 1.18.1

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:
```
Update go version to 1.18.1
```

### CODE REVIEW

**Comment by cpanato** [comment]
@jayesh-srivastava is CAPI using go1.18 already?

**Comment by jayesh-srivastava** [comment]
@cpanato No, actually. I thought it was updated but no. Let's wait till then?

**Comment by cpanato** [comment]
> @cpanato No, actually. I thought it was updated but no. Let's wait till then?

yes

**Comment by cpanato** [comment]
this was done in https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/663

thanks for your help and contribution

**Pull request closed without merging**
