### PR TITLE
Update klog dependency to v2

### PR DESCRIPTION
**Pull request by stmcginnis**
**What this PR does / why we need it**:

The klog v1 dependency used is quite old now, and the k/k repo has
switched to more recent v2 versions for quite some time now.

This updates klog usage to use the v2 package version.

**Special notes for your reviewer**:

This is part of an overall effort along with updating the k-sigs/cluster-api repo here:

https://github.com/kubernetes-sigs/cluster-api/pull/4284

/kind cleanup

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by stmcginnis** [comment]
Rebased on master to resolve conflict.

**Review by cpanato — APPROVED** [review]
/lgtm
/approve

**Comment by cpanato** [comment]
thanks @stmcginnis for your PR and sorry for the delay

**Pull request merged**
