### PR TITLE
⚠️ Remove v1alpha4 API types

### PR DESCRIPTION
**Pull request by vincepri**
**What type of PR is this?**

**What this PR does / why we need it**:

These APIs have been deprecated in their upstream counterpart, and soon be removed.

Let's remove them in the next version?

/kind api-change

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Remove v1alpha4 API types
```

### CODE REVIEW

**Comment by vincepri** [comment]
/hold

for tests / consensus

**Review by cpanato — APPROVED** [review]
thank you @vincepri 
/approve
/lgtm

will wait for @richardcase then we can lift the hold

**Comment by damdo** [comment]
@vincepri @cpanato The `v1alpha3` API got removed by https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/1115, which just merged. So this PR will need updating in title/release-notes/code to only target `v1alpha4`.

**Comment by richardcase** [comment]
Looks good to me. After the rebase lets get this in

**Comment by richardcase** [comment]
Seems good to me. After a rebase i think we are good to merge this.

**Comment by damdo** [comment]
Thanks! I'd rename the commit/PR title to just v1alpha4 API types, as the v1alpha3 were removed in the CAPI 1.6.x bump PR. Then LGTM

**Review by damdo — COMMENTED** [review]
Thanks!
/lgtm

**Pull request merged**
