### PR TITLE
Update CAPI to v1.2.0

### PR DESCRIPTION
**Pull request by cpanato**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

- Update CAPI to v1.2.0

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Update CAPI to v1.2.0
```

### CODE REVIEW

**Comment by cpanato** [comment]
ok ready
/assign @dims @pydctw @richardcase @Prajyot-Parab

**Comment by dims** [comment]
@cpanato do we want to override the apidiff failure?

**Comment by cpanato** [comment]
the diff is okay, checked the capz to see and they have similar, we are good

/override pull-cluster-api-provider-gcp-apidiff

**Comment by cpanato** [comment]
> @cpanato do we want to override the apidiff failure?

done

**Pull request merged**
