### PR TITLE
Update dependencies for v0.4.3

### PR DESCRIPTION
**Pull request by sayantani11**
**What type of PR is this?**

**What this PR does / why we need it**:
Upgrade to CAPI v0.4.3
Upgrade dependencies for v0.4.3
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Upgrade to v0.4.3
```

### CODE REVIEW

**Comment by sayantani11** [comment]
Just to see if this works🙂

**Comment by sayantani11** [comment]
@cpanato if @jayesh-srivastava is okay with that, guess we can merge this as it is not giving any errors. Then, we could move for the next release I guess.

**Comment by jayesh-srivastava** [comment]
@sayantani11 Yeah totally cool!

**Review by cpanato — APPROVED** [review]
/lgtm
/approve

thanks!

**Pull request merged**
