### PR TITLE
Fix GitHub Actions for Links 

### PR DESCRIPTION
**Pull request by hrittikhere**
/kind bug
/kind documentation

**What this PR does / why we need it**:

Fixes https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/622

### CODE REVIEW

**Comment by hrittikhere** [comment]
So tests do pass. Now if we can merge this and run all the checks again for docs we can find if our problem is solved or not. For local tests they stand to be solved

**Comment by cpanato** [comment]
/approve
/lgtm

thanks

**Pull request merged**
