### PR TITLE
Better activity log and don't fail when there are no instances

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by vincepri** [comment]
@dims We had a bug upstream that broke master which has been fixed a little ago https://github.com/kubernetes-sigs/cluster-api/pull/1464

The corresponding image was also rebuilt

**Comment by dims** [comment]
@vincepri aha! thanks. that helps

**Pull request merged**
