### PR TITLE
Update CAPI to v0.4.0-beta.0

### PR DESCRIPTION
**Pull request by cpanato**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Update CAPI to v0.4.0-beta.0

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Update CAPI to v0.4.0-beta.0
```

### CODE REVIEW

**Comment by cpanato** [comment]
similar work was done in CAPZ: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1421

**Review by vincepri — APPROVED** [review]
/lgtm

**Pull request merged**
