### PR TITLE
Add proposal and scaffolding for managed Kubernetes in CAPG

### PR DESCRIPTION
**Pull request by richardchen331**
/kind documentation

**What this PR does / why we need it**:
Add proposal and scaffolding for managed Kubernetes in CAPG (https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/512)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
- Add proposal for managed Kubernetes in CAPG
- Add scaffolds for managed Kubernetes in CAPG and defines the API types
```

### CODE REVIEW

**Comment by richardcase** [comment]
Thanks for creating this @richardchen331

For @cpanato & @pydctw - myself & @richardchen331 have added a task list to the GKE issue, #512 , based on this proposal. We thought we'd proceed with implementation and then refactor based on any feedback from the proposal as needed as we go along.....just to speed things up.

**Comment by cpanato** [comment]
please rebase

**Comment by richardchen331** [comment]
@cpanato The PR is rebased. Could you help review it when you get chance? Thanks! cc @richardcase

**Comment by richardchen331** [comment]
> This looks good to me.....it's worth calling out that this is the basis for the other open PRs and all the code here will not be used until a later PR uses and enables the GKE functionality.
> 
> @richardchen331 - a couple of very minor comments:
> 
> * The release note should probably be updated to include the fact that this also scaffolds the projects and defines the API types
> * Do you think it's possible to squash some of the commits? We don't have to squash to 1 commit, but for instance the last 2 could be squashed.

Sounds good. I've updated the release note and squash the commits (2 left, 1 for the proposal, 1 for the scaffolds). Please let me know if you have other feedback :)

**Comment by cpanato** [comment]
lgtm as well, can we plan as a follow up to have some tests for that?

**Comment by richardcase** [comment]
> lgtm as well, can we plan as a follow up to have some tests for that?

@cpanato - yes for sure 👍 Before we allow enabling of the controllers (via feature flag) we will make sure we have tests in place (unit and e2e).

**Comment by richardcase** [comment]
@richardchen331 - theres one small lint error:

```
Error: File is not `goimports`-ed (goimports)
```

Any chance you'd be able to take a look at that? Then i think we can merge 🎉

**Comment by richardchen331** [comment]
@cpanato @richardcase I created another PR with only the proposal (https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/801), could you help review and approve it? I think I'll be able to run the lint test myself after that without asking you to run it every time :) Thanks!

**Comment by richardcase** [comment]
> @cpanato @richardcase I created another PR with only the proposal (#801), could you help review and approve it? I think I'll be able to run the lint test myself after that without asking you to run it every time :) Thanks!

Ah yes, as you won't be a first-time contributor.

**Comment by richardcase** [comment]
Thanks @cpanato  🧙 

/lgtm

**Pull request merged**
