### PR TITLE
update api to v1beta1

### PR DESCRIPTION
**Pull request by cpanato**
**What type of PR is this?**

/kind feature
/kind api-change

**What this PR does / why we need it**:

update api to v1beta1

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
update api to v1beta1
```

### CODE REVIEW

**Comment by cpanato** [comment]
all good 
/hold cancel

**Comment by cpanato** [comment]
lets wait for this change as well https://github.com/kubernetes/test-infra/pull/24202

/hold

**Review by fabriziopandini — COMMENTED** [review]
changes lgtm from a quick check, great to see this happening!

**Comment by cpanato** [comment]
/test pull-cluster-api-provider-gcp-capi-e2e
/test pull-cluster-api-provider-gcp-conformance
/test pull-cluster-api-provider-gcp-conformance-ci-artifacts

retriggering

**Pull request merged**
