### PR TITLE
Update calico v.3.25.0 for E2E testing

### PR DESCRIPTION
**Pull request by meobilivang**
**What type of PR is this?**

**What this PR does / why we need it**:

Update `calico.yml` manifest launching Calico `v.3.25.0` on E2E test infra. Follow the suggested latest version `v.3.25.0` in #863 

**Special notes for your reviewer**:

> Summary of the changes in the updated file

**1. Newer/Updated attributes on CRDs:**
- `BGPConfiguration`
- `FelixConfiguration`

**2. Bump images’ version from `v.3.24.5` to `v.3.25.0`:**
- `node`
- `cni`
- `kube-controllers`

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cpanato** [comment]
@meobilivang thanks for this PR, there is a codespell issue can you fix that? thanks

**Comment by meobilivang** [comment]
Thanks for taking a look @cpanato  @richardcase  🙇 I think it's all ready to 🚀 now.

It's funny as this spelling error was a part of Calico's `v.3.25.0` official release ([here](https://github.com/projectcalico/calico/blob/3f7fe4d290541bbdd73c97bdc89a29a29855a48a/manifests/calico.yaml#L1145)) 😆 And they spent quite a bit of effort fixing "overriden" to "overridden" across the project (https://github.com/projectcalico/calico/commit/0c4ccb816f281b673ccd3b77eb3b89a6e7277035)

**Review by cpanato — APPROVED** [review]
thank you
/lgtm
/approve

**Pull request merged**
