### PR TITLE
:running: Remove clusterctl dependency from create-cluster

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

### CODE REVIEW

**Comment by joonas** [comment]
Overall it looks good, but I wonder if the `create-cluster` target has become large enough to warrant being turned in to a separate bash script?

**Comment by vincepri** [comment]
Probably, but I'd leave it for another time. It's only used for development or e2e tests right now

**Comment by vincepri** [comment]
Conformance is failing because of the data secret name, which will be fixed in another PR

**Pull request merged**
