### PR TITLE
CAPI: Updated CAPI to v0.4.3

### PR DESCRIPTION
**Pull request by jayesh-srivastava**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Updates CAPI to v0.4.3

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:
```release-note
Update CAPI to v0.4.3
```

### CODE REVIEW

**Comment by sayantani11** [comment]
@jayesh-srivastava Try running `go mod tidy` after making the changes and also run `make generate` and `make verify`. I guess that should do it. Most probably. Try going through the errors

**Comment by sayantani11** [comment]
`go: k8s.io/api@v0.21.3: missing go.sum entry; to add it:`
`make: *** [Makefile:261: docker-build] Error 1`

The makefile is failing for that most probably because I have faced a similar issue in the past

**Comment by jayesh-srivastava** [comment]
I already ran `go mod tidy`. Will run the other two commands.

**Comment by cpanato** [comment]
closing in favor of https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/427

/close

**Pull request closed without merging**
