### PR TITLE
Remove Hardcoded failureDomain in Template

### PR DESCRIPTION
**Pull request by evanfreed**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/683

**Special notes for your reviewer**:

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Removes hardcoding failureDomain in the default cluster-template.yaml
```

Signed-off-by: Evan Freed <evan.freed@protonmail.ch>

/kind bug

### CODE REVIEW

**Comment by pydctw** [comment]
@evanfreed, a great catch and thanks for the PR. The hard-coded failure domain is not need anymore.

/lgtm

**Review by cpanato — APPROVED** [review]

**Pull request merged**
