### PR TITLE
Create CAPG book from existing docs

### LINKED ISSUE #490: Sorting the CAPG documentation into a book
/kind feature

There are still a few improvements needed in CAPG documentation, but at this moment we can still work on the book. This will be something similar to: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/858
It will be better for new contributors or will provide easier usage to the users, apart from this it will also help in better management of docs.

We can have the CAPG docs hosted on Netlify site and request for a new site from the K8s org. 
We can iterate over the content of the book later, but for now can just set up the site with the existing topics.

**Note:** Only people with owner rights in a repository can deploy on a Netlify site.

### PR DESCRIPTION
**Pull request by salasberryfin**
/kind feature

**What this PR does / why we need it**:

This PR consolidates the existing documentation into a first version of the CAPG book.

Once this initial version is published, we can iterate over the contents and improve the user/developer experience.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #490 

**Special notes for your reviewer**:

This PR is still WIP until https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/1131 is approved and merged.

**TODOs**:

- [x] squashed commits
- [x] includes documentation
- [ ] adds unit tests

**Release note**:
```release-note
Publish CAPG book
```

### CODE REVIEW

**Comment by richardcase** [comment]
@salasberryfin now #1131 has merged can this be moved from wip?

**Comment by salasberryfin** [comment]
I was hoping that we could have the [netlify site](https://github.com/kubernetes/org/issues/4736) before, but it's not blocking us from having this reviewed and merged.

**Comment by richardcase** [comment]
Thanks @salasberryfin 

/approve

**Comment by cpanato** [comment]
/lgtm
/approve

thanks

**Pull request merged**
