### PR TITLE
GCPManagedControlPlane changes to support various GKE features

### PR DESCRIPTION
**Pull request by dantiandb**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
There's multiple features provided by GKE and supported by [contaienrpb](https://pkg.go.dev/cloud.google.com/go/container/apiv1/containerpb) that CAPG should also support for (more) completeness of its managed K8s support.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/1023

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [x] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
Add support for the following features for GKE clusters as defined in https://pkg.go.dev/cloud.google.com/go/container/apiv1/containerpb#Cluster
- ClusterIpv4Cidr
- AddonsConfig
  - DnsCacheConfig
  - GcePersistentDiskCsiDriverConfig
- ResourceLabels
- IPAllocationPolicy
   - UseIpAliases
   - ClusterSecondaryRangeName
   - ServicesSecondaryRangeName
   - ClusterIpv4CidrBlock
   - ServicesIpv4CidrBlock
- MaintenancePolicy
- NetworkConfig
   - DnsConfig
   - DatapathProvider
- DefaultMaxPodsConstraint
- PrivateClusterConfig
- ShieldedNodes
- WorkloadIdentityConfig
- LoggingConfig
```

### CODE REVIEW

**Review by cpanato — COMMENTED** [review]
/ok-to-test

**Comment by richardcase** [comment]
This is some overlap with #936 created by @aniruddha2000

**Pull request closed without merging**
