### PR TITLE
[compute/instances]: Fix subnet resource path. 🐛

### PR DESCRIPTION
**Pull request by dilyevsky**
**What this PR does / why we need it**:

Fixes a stalled gcpmachine creation when `GCPMachine.Spec.Subnet` is specified.

### CODE REVIEW

**Comment by cpanato** [comment]
i'm checking the error, looks like it is related to the image-builder

**Comment by dilyevsky** [comment]
@cpanato thanks, my second PR that I rebased on master has the same error now...

**Comment by cpanato** [comment]
@dilyevsky you can rebase now, it is fixed here https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/332

**Comment by dilyevsky** [comment]
@rsmitty thanks!

**Pull request merged**
