### PR TITLE
Update k8s version to latest 1.22 patch version

### PR DESCRIPTION
**Pull request by jayesh-srivastava**
**What type of PR is this?**

**What this PR does / why we need it**:
Updates k8s version to v1.22.3.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:
```
Updates k8s versions to v1.22.3.
```

### CODE REVIEW

**Review by cpanato — CHANGES_REQUESTED** [review]
thanks, looks good for a initial change

need to update in a few other places as well

- Tiltfile
- scripts/ci-e2e.sh
- hack/ci/e2e-conformance.sh

**Comment by jayesh-srivastava** [comment]
> thanks, looks good for a initial change
> 
> need to update in a few other places as well
> 
> * Tiltfile
> * scripts/ci-e2e.sh
> * hack/ci/e2e-conformance.sh

Updated!

**Comment by cpanato** [comment]
waiting https://github.com/kubernetes/test-infra/pull/24342

**Comment by sayantani11** [comment]
> thanks, looks good for a initial change
> 
> need to update in a few other places as well
> 
> * Tiltfile
> * scripts/ci-e2e.sh
> * hack/ci/e2e-conformance.sh

@cpanato Two of the changes are been marked as good first issue, and here's the PR https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/461
@jayesh-srivastava Can you make changes for the rest? As that PR was made before and will not do justice to the new contributor😓

**Comment by cpanato** [comment]
the pr that update the jobs are merged https://github.com/kubernetes/test-infra/pull/24551
lets retest this

/retest

**Review by cpanato — APPROVED** [review]
thanks @jayesh-srivastava 
/approve
/lgtm

**Pull request merged**
