### PR TITLE
Fix Typo to `prerequisites.md`

### PR DESCRIPTION
**Pull request by hrittikhere**
/kind documentation

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
thanks
/ok-to-test
/approve
/lgtm

**Comment by hrittikhere** [comment]
@cpanato do I need to do anything for the broken links? I didn't introduce these changes and also if  I visit these links the site opens.

**Comment by cpanato** [comment]
@hrittikhere will be good to fix that :)

**Comment by hrittikhere** [comment]
@cpanato so I am replacing this with https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key as we don't need an enterprise edition doc. Also how to test lint locally?

**Comment by hrittikhere** [comment]
Hey @cpanato 
I think there might be some issue with the action impelentation as the link can be perfectly accessed via a WebUI. Now after further investigation via curl we can see:

```html
<div id='message'>
<h2>The request is blocked.</h2></div>
<div id='errorref'>
<span>0/ByiYgAAAAD0Jl+OyjIrTI2PolL1vAbHTU5aMjIxMDYwNjE0MDI5ADU5NmQ3OGEyLWNhNWYtNDc5ZC1iY2RjLTA4MzU4MzMxNzRiMg==</span>
</div>
```
image

So the request is blocked via GitHub which we don't have any control over except to file an issue with the author of https://github.com/gaurav-nelson/github-action-markdown-link-check

Do you have any better alternatives or suggestions?

**Comment by hrittikhere** [comment]
I found a lead and we need to move forward with this change: https://github.com/tcort/markdown-link-check/issues/201#issuecomment-1110242146

This issue is not just bothering us as we see at https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/136 

If you want I can look into it and file a PR

**Comment by cpanato** [comment]
sounds good

**Comment by hrittikhere** [comment]
Filling a new PR for the link checks? Or should I add in the similar?

**Comment by cpanato** [comment]
open a new pr

**Comment by cpanato** [comment]
please rebase when https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/623 gets merged
thanks

**Review by cpanato — CHANGES_REQUESTED** [review]
plase squash the commits into one

**Review by cpanato — APPROVED** [review]
thanks!

**Pull request merged**
