### PR TITLE
Replace Windows with Windows+WSL2

### LINKED ISSUE #439: Replace Windows with Windows + WSL2
/kind documentation

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Currently windows isn't supported by the project at this moment. But for a windows user the project can be set up in a WSL2 system. This will help the new contributors better about setting up of the project.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Under the docs folder, make necessary changes.
Refer to: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1621

For example:
`chocolatey install jq` on Windows will be replaced by `sudo apt install jq` on Windows+WSL2

### PR DESCRIPTION
**Pull request by BLasan**
**What type of PR is this?**
/kind documentation

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #439 

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

`NONE`

### CODE REVIEW

**Comment by sayantani11** [comment]
LGTM!!
Thanks for the PR
cc @cpanato

**Review by cpanato — COMMENTED** [review]
/ok-to-test

**Comment by BLasan** [comment]
@sayantani11 @cpanato  Lint documentation is failing. There were some errors related to the dead links found which are not added by me.

**Comment by cpanato** [comment]
@BLasan but can you fix it?

**Comment by BLasan** [comment]
> @BLasan but can you fix it?

Shall I add the fixes to this PR?

**Comment by sayantani11** [comment]
> @BLasan but can you fix it?

It's failing for all the PRs for some links, I will add a PR fixing it

**Comment by sayantani11** [comment]
> @BLasan but can you fix it?

@cpanato This is because the meeting links in the readme are non-existent. I will fix it in the next PR.

**Comment by BLasan** [comment]
@sayantani11 Updated the PR

**Review by cpanato — COMMENTED** [review]
I think we should keep the chocolatey instructions as well. Or this is the normal process when using windows?
asking that because I don't use windows

and did you try those steps on a windows machine?

**Comment by BLasan** [comment]
Dead link found - `[✖] https://github.com/kubernetes/release/tree/master/cmd/cip-mm`

**Comment by cpanato** [comment]
> https://github.com/kubernetes/release/tree/master/cmd/cip-mm

please update that to `https://github.com/kubernetes-sigs/promo-tools/tree/main/cmd/cip-mm`

**Comment by BLasan** [comment]
> > https://github.com/kubernetes/release/tree/master/cmd/cip-mm
> 
> please update that to `https://github.com/kubernetes-sigs/promo-tools/tree/main/cmd/cip-mm`

Updated

**Comment by sayantani11** [comment]
> I think we should keep the chocolatey instructions as well. Or this is the normal process when using windows? asking that because I don't use windows
> 
> and did you try those steps on a windows machine?

We can keep it, but the running the project we require a nix environment. So even if we set that up using windows we won't be able to use somethings to their potential. So it is better to use Windows Subsystem linux 2 which will provide the required nix environment. All the commands will be similar to that of any Linux system. Chocalatey is used when we try setting up the project in a Windows environment using windows powershell or command line terminal. So we can keep it, but setting up the project in a windows environment will cause problems to the contributor.

**Comment by BLasan** [comment]
> > I think we should keep the chocolatey instructions as well. Or this is the normal process when using windows? asking that because I don't use windows
> > and did you try those steps on a windows machine?
> 
> We can keep it, but for running the project we require a nix environment. So even if we set that up using windows we won't be able to use this to their potential. So it is better to use Windows Subsystem Linux 2 which will provide the required nix environment. All the commands will be similar to that of any regular Linux system. Chocolatey is used when we try setting up the project in a Windows environment using windows PowerShell or command line terminal. So we can keep it no issues, setting up the project in a windows environment will cause problems to the contributor. To avoid confusion its better we remove it. This can be confirmed by me, as I have personally experienced this issue.

Hi, could you please approve the remaining workflows?

**Review by cpanato — APPROVED** [review]
thanks!
/lgtm
/approve

**Pull request merged**
