### PR TITLE
chore: bump CAPI to v1.4.4

### PR DESCRIPTION
**Pull request by richardcase**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

This bumps CAPI to v1.4.4

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Bump CAPI to v1.4.4
```

### CODE REVIEW

**Comment by richardcase** [comment]
@cpanato - fyi, i will fix the e2e on Monday

**Comment by damdo** [comment]
It looks like the E2Es are failing due to kind.
Which is potentially the same issue we faced in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4372
Should we do a similar [replacement](https://github.com/kubernetes-sigs/cluster-api-provider-aws/commit/1f9f2dbb56524e181d373ff912de7b45262eb145) to try and move this one forward?

**Comment by damdo** [comment]
It looks like the E2Es are failing due to kind.
Which is potentially the same issue we faced in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4372
Should we take a similar approach to try and move this one forward @richardcase ?

**Comment by richardcase** [comment]
@cpanato  - do you think it's ok to override the apidiff for this?

**Comment by cpanato** [comment]
agree!
but we dont need because that is not required

**Review by cpanato — APPROVED** [review]
cool! this is super nice thank you
/lgtm
/approve

**Comment by cpanato** [comment]
@richardcase i tomorrow i will create the jobs to prepare for the 1.4 release, do we want anything else in the new release?

**Comment by richardcase** [comment]
> @richardcase i tomorrow i will create the jobs to prepare for the 1.4 release, do we want anything else in the new release?

Thanks @cpanato . I'll go through the open PRs and see if there are any must haves.

**Comment by cpanato** [comment]
> > @richardcase i tomorrow i will create the jobs to prepare for the 1.4 release, do we want anything else in the new release?
> 
> Thanks @cpanato . I'll go through the open PRs and see if there are any must haves.

https://github.com/kubernetes/test-infra/pull/30067

**Pull request merged**
