### PR TITLE
Update e2e-conformance.sh to use image-builder deps-gce target for installing dependencies

### PR DESCRIPTION
**Pull request by detiber**
**What this PR does / why we need it**:

Update e2e-conformance.sh to use image-builder deps-gce target for installing dependencies

Depends on: https://github.com/kubernetes/test-infra/pull/18531 and an update to the kubekins-e2e image to include the new python3 packages before this will work correctly.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by detiber** [comment]
It looks like there is also an issue in image-builder with how the python2 fallbacks were being handled, created https://github.com/kubernetes-sigs/image-builder/pull/312 to remove those in favor of explicit use of python3/pip3

**Comment by gab-satchi** [comment]
let's /hold until python3 bump is sorted out

**Comment by ncdc** [comment]
Got past the ansible error. Now this:

```
hack/ensure-packer.sh
mkdir: cannot create directory '.local': Permission denied
```

Which comes from the following (from the image-builder repo):

```
# Change directories to the parent directory of the one in which this
# script is located.
cd "$(dirname "${BASH_SOURCE[0]}")/.."

source hack/utils.sh

if command -v packer >/dev/null 2>&1; then exit 0; fi

mkdir -p .local/bin && cd .local/bin
```

In this job, the image-builder repo is in `/home/prow/go/src/sigs.k8s.io/image-builder/images/capi`, which is one of the `extra_refs` from the Prow job. Maybe it's read-only?

**Comment by ncdc** [comment]
Continuing this discussion in https://github.com/kubernetes-sigs/image-builder/issues/342

**Pull request merged**
