### PR TITLE
[WIP]Cluster template for ipv6

### PR DESCRIPTION
**Pull request by sayantani11**
**What type of PR is this?**

**What this PR does / why we need it**:
This PR adds cluster template for ipv6

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
Related to #451 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Cluster template for ipv6
```

### CODE REVIEW

**Review by cpanato — CHANGES_REQUESTED** [review]
@sayantani11 thanks for your PR but this does not work today in capg (https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/api/v1beta1/types.go#L115-L120) we need to implement this support in the service to be able to use ipv6

**Comment by sayantani11** [comment]
> @sayantani11 thanks for your PR but this does not work today in capg (https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/api/v1beta1/types.go#L115-L120) we need to implement this support in the service to be able to use ipv6
> 
> if you want to implement the code changes that will be awesome, otherwise we can create an issue to add the ipv6 support and close this PR for now

I can do the necessary changes then, will keep this on hold and will try to do this in a separate PR

**Comment by sayantani11** [comment]
Will reopen after ipv6 support

**Pull request closed without merging**
