### PR TITLE
Update README.md

### LINKED ISSUE #487: Typo in README.md
There's a small typo at `line 65` in the `README.md` file with the correct word being `environment`. Also at `line 68`, `this` should be replaced with `these`. Contributors should also look for other possible typos and try to correct them as well.

### PR DESCRIPTION
**Pull request by wondersumanth**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
This PR is to update the documentation

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #487

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [x] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by jayesh-srivastava** [comment]
@wondersumanth You'll have to sign the CLA first. Also, there are more typos in the README.md file if you check thoroughly.

**Comment by wondersumanth** [comment]
> @wondersumanth You'll have to sign the CLA first. Also, there are more typos in the README.md file if you check thoroughly.

@jayesh-srivastava  Sure. I'm checking both the points you have mentioned.

**Comment by wondersumanth** [comment]
I signed it

**Comment by jayesh-srivastava** [comment]
@wondersumanth You are required to squash the two commits into one. Two different commits are unnecessary.

**Comment by wondersumanth** [comment]
> @wondersumanth You are required to squash the two commits into one. Two different commits are unnecessary.

**Comment by wondersumanth** [comment]
> @wondersumanth You are required to squash the two commits into one. Two different commits are unnecessary.

@jayesh-srivastava Its done.

**Review by jayesh-srivastava — APPROVED** [review]
lgtm

**Comment by cpanato** [comment]
thanks
/approve
/lgtm

**Pull request merged**
