### PR TITLE
Remove ginkgo / gomega

### LINKED ISSUE #44: Remove ginkgo code (introduced by kubebuilder migration)
We previously went through and removed all of the ginkgo code. Then it came back. There is only a tiny bit of it in this repo and the sooner we take it out the easier it will be to do so.

This should be relatively easy, even for someone new to the project.

/cc @krousey

### PR DESCRIPTION
**Pull request by roberthbailey**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #44

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by krousey** [comment]
/lgtm

and thank you

**Comment by roberthbailey** [comment]
@lucasnorman - sorry I didn't see your PR. There is a similar bug open in the main cluster-api repo (which I won't have time to address soon) if you want to take a look at starting to pull out ginkgo there.

**Comment by justinsb** [comment]
/lgtm

`Expect(gomega).NotTo(HaveOccurred())` :-)

**Pull request merged**
