### PR TITLE
Added flannel.md to the docs

### PR DESCRIPTION
**Pull request by sayantani11**
**What type of PR is this?**

**What this PR does / why we need it**:
I am currently trying to add a few docs to CAPG that will enhance the project. I am still browsing through other CAP* projects in in order understand the enhancement. 
Any sort of help related to addition to the docs will be helpful.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [x] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Addition of flannel.md to the docs
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
looks good, a nonblocking question, did you try this to bootstrap the cluster?
any updates we can apply in a follow up

/lgtm
/approve

**Comment by sayantani11** [comment]
@cpanato No I haven't actually.

**Comment by cpanato** [comment]
can you try?

**Comment by sayantani11** [comment]
@cpanato Have to see. I actually pasted the link on the slack, of what I was trying to do.

**Pull request merged**
