### PR TITLE
add verify-tiltfile target

### PR DESCRIPTION
**Pull request by sayantani11**
**What type of PR is this?**

**What this PR does / why we need it**:
The PR adds a target that verifies tiltfile

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
A part of #510 
**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
verify-tiltfile target  added
```

### CODE REVIEW

**Comment by sayantani11** [comment]
@cpanato Can you help with the error?

**Comment by cpanato** [comment]
@sayantani11 in this case you need to run your new makefile rule `make format-tiltfile` and commit the changes that will fix the tiltfile

**Comment by sayantani11** [comment]
cc @cpanato

**Comment by pydctw** [comment]
Could you squash the commits?

Also, FYI, we normally use rebasing instead of merging. See https://kubernetes.io/docs/contribute/new-content/open-a-pr/#merge-conflicts-and-rebasing.

**Comment by pydctw** [comment]
> Actually there was some issue when I was trying to rebase the PR in the local system. It has happened a few times, and I wasn't able to solve it. The same issue was faced in this PR as well or else I usually do squash my PRs. So if possible can we work without squashing?

Hmm, that is interesting. I've pulled down your PR locally and rebased successfully after resolving merge conflicts. 

Could you try again? Let me know how I can help.

**Comment by cpanato** [comment]
@sayantani11 do you need any help with the rebase?

**Comment by sayantani11** [comment]
pheww!!! @cpanato @pydctw seems like I finally got it fixed 🤗

**Review by cpanato — APPROVED** [review]
thanks
/approve
/lgtm

**Pull request merged**
