### PR TITLE
CAPI: Updated CAPI to v0.4.3

### PR DESCRIPTION
**Pull request by jayesh-srivastava**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Update CAPI to v0.4.3

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:
```release-note
Update CAPI to v0.4.3

```

### CODE REVIEW

**Comment by sayantani11** [comment]
@jayesh-srivastava I guess we need generate the go.mod file and also run `make generate` or something from the root directory to generate the changed file. I guess the errors will be avoided then.

**Comment by jayesh-srivastava** [comment]
@sayantani11 I think there are some values that need to be added in `go.sum` file.

**Comment by sayantani11** [comment]
@jayesh-srivastava yeah I guess that has something to do with the go.mod
I remember @cpanato did run a command that changed the values in the go.sum
Guess you need to ask him!

**Pull request closed without merging**
