### PR TITLE
Add pre-requisites for default network setup

### PR DESCRIPTION
**Pull request by Ankitasw**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
This PR elaborates the pre-requisite steps for network creation

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**TODOs**:

- [ ] squashed commits
- [x] includes documentation
- [ ] adds unit tests

**Release note**:
```release-note
Improved pre-requisite doc
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

thanks for improving the docs

**Comment by dims** [comment]
@cpanato do we need the teardown steps too?

/approve
/lgtm
/hold

**Comment by cpanato** [comment]
> @cpanato do we need the teardown steps too?
> 
> /approve
> /lgtm
> /hold

would be good to have as well

@Ankitasw is it possible to add?

**Comment by Ankitasw** [comment]
@cpanato you mean deleting the firewall rules, routers, networks etc.?

**Comment by cpanato** [comment]
> @cpanato you mean deleting the firewall rules, routers, networks etc.?

yes

**Comment by Ankitasw** [comment]
will it be required in this case, as I see for other providers, we have not provided such teardown steps?

**Comment by cpanato** [comment]
it is not required, but if you don't want to spend additional $$ maybe is good to clean up everything after you finish the development part

**Comment by Ankitasw** [comment]
> t if you don't want to spend additional $$ maybe is good to clean up everything after you finish the development part

Agreed :) shall we have those steps in pre-requisite doc itself?

**Comment by cpanato** [comment]
sgmt @Ankitasw thanks for doing this

**Review by cpanato — APPROVED** [review]
/lgtm thanks for adding that


I'm wondering if these operations should be handle in the CAPG, what do you think @dims?

**Comment by dims** [comment]
/approve
/lgtm

let's ask CAPA/CAPZ folks what they do and we should try to do the same in CAPG. in any case we'll need these instructions to cleanup from say a broken install etc

**Comment by Ankitasw** [comment]
@dims i think this PR is still on hold, do we want to keep it on hold?

**Pull request merged**
